services:
  - type: web
    name: march-madness-predictor
    env: python
    buildCommand: cd march_madness_predictor && pip install -r requirements.txt
    startCommand: cd march_madness_predictor && gunicorn --config gunicorn_config.py wsgi:server
    envVars:
      - key: PYTHON_VERSION
        value: 3.9.12 